//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by w10_pc_user.rc
//
#include "StringTable.h"

#ifndef		__MAIN_RESOURCES_H__
#define		__MAIN_RESOURCES_H__

#define WWE_ID                          0
#define IDC_MYICON                      2
#define IDD_COMBO_LIST                  100
#define IDC_OPTIONS                     101
#define IDD_W10_PC_USER_DIALOG          102
#define IDC_APPLY                       102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDD_MAIN                        103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_W10_PC_USER                 107
#define IDI_SMALL                       108
#define IDC_W10_PC_USER                 109
#define IDR_MAINFRAME                   128
#define IDD_SETTINGS                    129
#define IDD_EDIT                        200
#define IDC_UNIT_TEXT                   201
#define IDD_BT_INIT                     202
#define IDC_EDIT                        202
#define IDD_TIMEZONE                    300
#define IDC_HOUR                        301
#define IDC_MINUTE                      302
#define IDD_COMBO_EDIT                  400
#define IDD_STEP                        500
#define IDC_RUN                         504
#define IDC_SWIM                        505
#define IDC_OTHER                       506
#define IDD_ALARM                       600
#define IDC_ALARM1                      601
#define IDC_SUN1                        602
#define IDC_MON1                        603
#define IDC_TUE1                        604
#define IDC_WED1                        605
#define IDC_THU1                        606
#define IDC_FRI1                        607
#define IDC_SAT1                        608
#define IDC_HOUR1                       609
#define IDC_MIN1                        610
#define IDC_ALARM2                      611
#define IDC_SUN2                        612
#define IDC_MON2                        613
#define IDC_TUE2                        614
#define IDC_WED2                        615
#define IDC_THU2                        616
#define IDC_FRI2                        617
#define IDC_SAT2                        618
#define IDC_HOUR2                       619
#define IDC_MIN2                        620
#define IDC_ALARM3                      621
#define IDC_SUN3                        622
#define IDC_MON3                        623
#define IDC_TUE3                        624
#define IDC_WED3                        625
#define IDC_THU3                        626
#define IDC_FRI3                        627
#define IDC_SAT3                        628
#define IDC_HOUR3                       629
#define IDC_MIN3                        630
#define IDC_ALARM4                      631
#define IDC_SUN4                        632
#define IDC_MON4                        633
#define IDC_TUE4                        634
#define IDC_WED4                        635
#define IDC_THU4                        636
#define IDC_FRI4                        637
#define IDC_SAT4                        638
#define IDC_HOUR4                       639
#define IDC_MIN4                        640
#define IDD_WEIGHT_HEIGHT               700
#define IDC_WEIGHT                      701
#define IDC_WEIGHT_KG                   702
#define IDC_KG                          703
#define IDC_WEIGHT_POUND                704
#define IDC_POUND                       705
#define IDC_HEIGHT                      706
#define IDC_HEIGHT_CM                   707
#define IDC_CM                          708
#define IDC_HEIGHT_INCH                 709
#define IDC_INCH                        710
#define IDC_COMM                        1000
#define IDC_MODE                        1000
#define IDC_SYNC                        1001
#define IDC_LANG                        1001
#define IDC_MSG                         1002
#define IDC_KEYTONE                     1002
#define IDC_BUTTON1                     1003
#define IDC_STOP_SYNC                   1003
#define IDC_MESSAGETONE                 1003
#define IDC_PROGRESS1                   1004
#define IDC_DOWNLOAD                    1004
#define IDC_VIBRATION                   1004
#define IDC_BUTTON2                     1005
#define IDC_UPDATE                      1005
#define IDC_BK_TIMEOUT                  1005
#define IDC_COMMIT                      1006
#define IDC_BK_LEVEL                    1006
#define IDC_COMBO1                      1007
#define IDC_ORIENTATION                 1007
#define IDC_COMBO2                      1008
#define IDC_USER_LOCATION               1008
#define IDC_CHECK1                      1009
#define IDC_SHOW_MAP                    1009
#define IDC_CHECK2                      1010
#define IDC_ANT_WEIGHT_SCALE            1010
#define IDC_CHECK3                      1011
#define IDC_ANT_FITNESS_EQUIPMENT       1011
#define IDC_EDIT1                       1012
#define IDC_RECORD_DATA_POINTS          1012
#define IDC_COMBO3                      1013
#define IDC_TIME_FORMAT                 1013
#define IDC_COMBO4                      1014
#define IDC_TIME_ZONE_1                 1014
#define IDC_EDIT2                       1015
#define IDC_DAYLIGHT_SAVING_1           1015
#define IDC_CHECK4                      1016
#define IDC_UNIT                        1016
#define IDC_SETTINGS                    1016
#define IDC_CHECK5                      1017
#define IDC_POSITION_UNIT               1017
#define IDC_CHECK6                      1018
#define IDC_AUTO_LAP                    1018
#define IDC_CHECK7                      1019
#define IDC_AUTO_PAUSE                  1019
#define IDC_COMBO5                      1020
#define IDC_AUTO_SCROLL                 1020
#define IDC_COMBO6                      1021
#define IDC_VIRTUAL_PARTNER             1021
#define IDC_COMBO7                      1022
#define IDC_PACE_SPEED                  1022
#define IDC_COMBO8                      1023
#define IDC_ANT_HEART_RATE_MONITOR      1023
#define IDC_ANT_HEART_RATE_DISPLAY      1024
#define IDC_ANT_FOOT_PAD                1025
#define IDC_CHECK8                      1026
#define IDC_ANT_FOOT_PAD_SOURCE         1026
#define IDC_COMBO9                      1027
#define IDC_ANT_FOOT_STEP_DISTANCE      1027
#define IDC_COMBO10                     1028
#define IDC_ANT_BIKE_WEIGHT             1028
#define IDC_COMBO11                     1029
#define IDC_ANT_BIKE_ODOMETER           1029
#define IDC_COMBO12                     1030
#define IDC_ANT_BIKE                    1030
#define IDC_COMBO13                     1031
#define IDC_ANT_BIKE_WHEEL_SIZE         1031
#define IDC_CHECK9                      1032
#define IDC_ANT_BIKE_SENSOR             1032
#define IDC_COMBO14                     1033
#define IDC_ANT_POWER_METER_SENSOR      1033
#define IDC_EDIT3                       1034
#define IDC_BLE_FINDER                  1034
#define IDC_EDIT4                       1035
#define IDC_GSENSOR_COMPASS_SENSOR      1035
#define IDC_EDIT5                       1036
#define IDC_GSENSOR_STEP_DISTANCE       1036
#define IDC_EDIT6                       1037
#define IDC_BLE_HEART_RATE              1037
#define IDC_EDIT7                       1038
#define IDC_TIME_ZONE_2                 1038
#define IDC_EDIT8                       1039
#define IDC_DAYLIGHT_SAVING_2           1039
#define IDC_COMBO15                     1040
#define IDC_GPS_TIMER_AUTO_UPDATE       1040
#define IDC_CHECK10                     1041
#define IDC_BT_NOTIFY_TONE_TIME         1041
#define IDC_COMBO16                     1042
#define IDC_BT_NOTIFY_VIBRATION_TIME    1042
#define IDC_CHECK11                     1043
#define IDC_BAROMETER_SENSOR            1043
#define IDC_COMBO17                     1044
#define IDC_THEME                       1044
#define IDC_COMBO18                     1045
#define IDC_METRONOME_STATE             1045
#define IDC_METRONOME_INTERVAL          1046
#define IDC_METRONOME_RING_TIME         1047
#define IDC_ALARM                       1048
#define IDC_TIME_ALERT                  1049
#define IDC_DIST_ALERT                  1050
#define IDC_CALORIE_ALERT               1051
#define IDC_HR_ALERT                    1052
#define IDC_HR_ALERT_MIN                1052
#define IDC_INTERVAL                    1053
#define IDC_REST                        1054
#define IDC_REPTS                       1055
#define IDC_WARM_UP                     1056
#define IDC_COOL_DOWN                   1057
#define IDC_GENDER                      1058
#define IDC_AGE                         1059
#define IDC_WEIGHT_HEIGHT               1060
#define IDC_LIFETIME_ATHLETE            1061
#define IDC_HR_ALERT_MAX                1062
#define IDC_AUTO_LAP_EXT                1064
#define IDC_BT_INIT                     2020
#define IDC_BT_INIT_BAR                 2021
#define CHT_ID                          10000

#define CHS_ID                          20000
#define IDC_STATIC                      -1

#endif		//__MAIN_RESOURCES_H__

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
